# Site settings
title: Alessandro Minoccheri
email: alessandro.minoccheri@gmail.com
description: perfection is not an option
twitter_username: minompi
github_username:  AlessandroMinoccheri

# Build settings
markdown: redcarpet
highlighter: rouge
redcarpet:
      extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
theme: jekyll-theme-minimal